# Generated by Django 4.1.4 on 2023-01-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('K', 'MODERATE'), ('L', 'LOW')], max_length=1)),
                ('status', models.CharField(choices=[('S', 'FINISHED'), ('P', 'IN PROGRESS'), ('N', 'NOT STARTED YET')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'priority', 'title'],
            },
        ),
    ]
